# Configuration for weighted average embedding strategy

database:
  chroma_db_path: "/Users/ck/Monarch/elder/emb_data/models/ada002"
  collection_name: "ada002_lrd_hpo_embeddings"
  similarity_measure: "COSINE"

runner:
  runner_type: "wgt_avg"
  model_type: "ada"
  nr_of_phenopackets: "10"
  nr_of_results: 10

processing:
  use_multiprocessing: true

output:
  output_dir: "./output"

data_paths:
  phenopackets_dir: "test_phenopackets"